<!DOCTYPE html>
<html>
<head>
	<title>My Product Landing Page</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<header>
		<nav>
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">Features</a></li>
				<li><a href="#">Pricing</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</nav>
	</header>
	<main>
		<section class="hero-section">
			<h1>Discover Our Product</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			<button>Learn More</button>
		</section>
		<section class="features-section">
			<h2>Our Features</h2>
			<div class="feature-box">
				<img src="feature1.png" alt="Feature 1">
				<h3>Feature 1</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="feature-box">
				<img src="feature2.png" alt="Feature 2">
				<h3>Feature 2</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="feature-box">
				<img src="feature3.png" alt="Feature 3">
				<h3>Feature 3</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
		</section>
		<section class="pricing-section">
			<h2>Pricing</h2>
			<div class="pricing-box">
				<h3>Basic</h3>
				<h4>$10/month</h4>
				<ul>
					<li>Feature 1</li>
					<li>Feature 2</li>
					<li>Feature 3</li>
				</ul>
				<button>Buy Now</button>
			</div>
			<div class="pricing-box">
				<h3>Pro</h3>
				<h4>$20/month</h4>
				<ul>
					<li>Feature 1</li>
					<li>Feature 2</li>
					<li>Feature 3</li>
					<li>Feature 4</li>
					<li>Feature 5</li>
				</ul>
				<button>Buy Now</button>
			</div>
			<div class="pricing-box">
				<h3>Premium</h3>
				<h4>$30/month</h4>
				<ul>
					<li>Feature 1</li>
					<li>Feature 2</li>
					<li>Feature 3</li>
					<li>Feature 4</li>
					<li>Feature 5
